apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: a8unkv477-java-springboot
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe-java-springboot:f7c2831874f0fd6f4be42c3e2ce4f7f5cd9b104a@sha256:382c62efd5a0e630778cb95a4f4859ffba9aea9e9754cb1a1a2920d185875e0a
          name: container-image
